
# Appendix D - Model Diagnostics
Additional Tables and illustrations for the convenience of the reader. Add illustrations they said; it will add value they said.

## Study 1
Model diagnostics were drawn for the full and null model in study 1. Rhat values in both models were equal to one, indicating convergence across all chains. Effective sample sizes for all fixed effects in the full model (Bulk ESS, mean = `r round(mean(S1.full.coef$ess_bulk), 0)`, range `r round(min(S1.full.coef$ess_bulk), 0)` - `r round(max(S1.full.coef$ess_bulk), 0)`) and the null model (Bulk ESS, mean = `r round(mean(S1.null.coef$ess_bulk), 0)`, range `r round(min(S1.null.coef$ess_bulk), 0)` - `r round(max(S1.null.coef$ess_bulk), 0)`) were > 1000, indicating reliable posterior estimations.

## Study 2
Model diagnostics were drawn for the full and null model in study 2. Rhat values in both models were equal to one, indicating convergence across all chains. Effective sample sizes for all fixed effects in the full model (Bulk ESS, mean = `r round(mean(S2.full.coef$ess_bulk), 0)`, range `r round(min(S2.full.coef$ess_bulk), 0)` - `r round(max(S2.full.coef$ess_bulk), 0)`) and the null model (Bulk ESS, mean = `r round(mean(S2.null.coef$ess_bulk), 0)`, range `r round(min(S2.null.coef$ess_bulk), 0)` - `r round(max(S2.null.coef$ess_bulk), 0)`) were > 1000, indicating reliable posterior estimations.

## Study 3
Model diagnostics were drawn for the full and null model in study 3. Rhat values in both models were equal to one, indicating convergence across all chains. Effective sample sizes for all fixed effects in the full model (Bulk ESS, mean = `r round(mean(S3.full.coef$ess_bulk), 0)`, range `r round(min(S3.full.coef$ess_bulk), 0)` - `r round(max(S3.full.coef$ess_bulk), 0)`) and the null model (Bulk ESS, mean = `r round(mean(S3.null.coef$ess_bulk), 0)`, range `r round(min(S3.null.coef$ess_bulk), 0)` - `r round(max(S3.null.coef$ess_bulk), 0)`) were > 1000, indicating reliable posterior estimations.
