
# Appendix C - Descriptive Statistics
```{r suppl-descriptives-S1, tab.cap = "Descriptive Analyses for Study 1.", eval = T}

#library(scales) 
# required for rounding pvalues, is part of tidyverse but needs to be loaded again? ## it occurs when functions are overwritten multiple times

rep.s1.freq <- rep.S1.bayes.data %>% 
  mutate(Age = paste0(agey, "-year-olds"),
         Condition = condition) %>% 
  group_by(Condition, Age, subid) %>% 
  summarise("correct" = mean(correct),
            "trials" = n()) %>% 
  ungroup() %>% 
  group_by(Condition, Age) %>%
   summarise(N = n_distinct(subid),
             trials = sum(trials),
             "trials/N" = round(sum(trials)/n_distinct(subid), 2),
             "M" = round(mean(correct)*100, 2),
             "SD" = round(sd(correct)*100, 2),
             p = pvalue(t.test((correct), mu = 0.5)$p.value, accuracy = .001),
             df= t.test((correct), mu = 0.5)$parameter,
             "t(N-1)" = round(t.test((correct), mu = 0.5)$statistic, 2),
             d = round(cohensD((correct), mu = 0.5), 2))

# # delete duplicate labels in age by turning age into character and replacing duplicates
rep.s1.freq$Condition <- as.character(rep.s1.freq$Condition)
rep.s1.freq$Condition[duplicated(rep.s1.freq$Condition)] <- ""

# kable(rep.s1.freq) %>%
# kable_styling(bootstrap_options = c("striped", "hover", "condensed"))

# apa_table(
#   rep.s1.freq
#   , caption = "Descriptive Statistics for Study 1"
#   , note = "This table was created by Gregor."
#   , escape = TRUE
# )

# apa_table(
#   rep.s1.freq,
#   caption = "Descriptive Statistics for Study 1",
#   escape = TRUE,
#   font_size = "small"
# )

ft <- flextable(rep.s1.freq) %>%
  theme_apa() %>%
  set_caption("suppl-descriptives-S1") %>%
  fontsize(size = 8, part = "all") %>%
  set_table_properties(layout = "autofit") %>%
  autofit()
ft


```
\newpage

```{r suppl-descriptives-S2, tab.cap = "Descriptive Analyses for Study 2.", eval = T}

#library(scales) 
# required for rounding pvalues, is part of tidyverse but needs to be loaded again? ## it occurs when functions are overwritten multiple times

rep.s2.freq <- rep.S2.bayes.data %>% 
  mutate(Age = paste0(agey, "-year-olds"),
         Condition = condition) %>% 
  group_by(Condition, Age, subid) %>% 
  summarise("correct" = mean(correct),
            "trials" = n()) %>% 
  ungroup() %>% 
  group_by(Condition, Age) %>%
   summarise(N = n_distinct(subid),
             trials = sum(trials),
             "trials/N" = round(sum(trials)/n_distinct(subid), 2),
             "M" = round(mean(correct)*100, 2),
             "SD" = round(sd(correct)*100, 2),
             p = pvalue(t.test((correct), mu = 0.5)$p.value, accuracy = .001),
             df= t.test((correct), mu = 0.5)$parameter,
             "t(N-1)" = round(t.test((correct), mu = 0.5)$statistic, 2),
             d = round(cohensD((correct), mu = 0.5), 2))

# # delete duplicate labels in age by turning age into character and replacing duplicates
rep.s2.freq$Condition <- as.character(rep.s2.freq$Condition)
rep.s2.freq$Condition[duplicated(rep.s2.freq$Condition)] <- ""

# kable(rep.s1.freq) %>%
# kable_styling(bootstrap_options = c("striped", "hover", "condensed"))

# apa_table(
#   rep.s2.freq
#   , caption = "Descriptive Statistics for Study 2"
#   , note = "This table was created by Gregor."
#   , escape = TRUE
# )

# apa_table(
#   rep.s2.freq,
#   caption = "Descriptive Statistics for Study 2",
#   escape = TRUE,
#   font_size = "small"
# )


ft <- flextable(rep.s2.freq) %>%
  theme_apa() %>%
  set_caption("suppl-descriptives-S2") %>%
  fontsize(size = 8, part = "all") %>%
  set_table_properties(layout = "autofit") %>%
  autofit()
ft

```
\newpage

```{r suppl-descriptives-S3, tab.cap = "Descriptive Analyses for Study 3.", eval = T}

#library(scales) 
# required for rounding pvalues, is part of tidyverse but needs to be loaded again? ## it occurs when functions are overwritten multiple times

rep.s3.freq <- rep.S3.bayes.data %>% 
  mutate(Age = paste0(agey, "-year-olds"),
         Condition = condition) %>% 
  group_by(Condition, Age, subid) %>% 
  summarise("correct" = mean(correct),
            "trials" = n()) %>% 
  ungroup() %>% 
  group_by(Condition, Age) %>%
   summarise(N = n_distinct(subid),
             trials = sum(trials),
             "trials/N" = round(sum(trials)/n_distinct(subid), 2),
             "M" = round(mean(correct)*100, 2),
             "SD" = round(sd(correct)*100, 2),
             p = pvalue(t.test((correct), mu = 0.5)$p.value, accuracy = .001),
             df= t.test((correct), mu = 0.5)$parameter,
             "t(N-1)" = round(t.test((correct), mu = 0.5)$statistic, 2),
             d = round(cohensD((correct), mu = 0.5), 2))

# # delete duplicate labels in age by turning age into character and replacing duplicates
rep.s3.freq$Condition <- as.character(rep.s3.freq$Condition)
rep.s3.freq$Condition[duplicated(rep.s3.freq$Condition)] <- ""

# kable(rep.s1.freq) %>%
# kable_styling(bootstrap_options = c("striped", "hover", "condensed"))

# apa_table(
#   rep.s3.freq,
#   caption = "Descriptive Statistics for Study 3",
#   escape = TRUE,
#   font_size = "small"
# )


ft <- flextable(rep.s3.freq) %>%
  theme_apa() %>%
  set_caption("suppl-descriptives-S3") %>%
  fontsize(size = 8, part = "all") %>%
  set_table_properties(layout = "autofit") %>%
  autofit()
ft

```

```{r symlit_rep_plottaskdifficulty, eval= F}

# aggregate proportion of correct choices and number of trials for each individual
rep_difficultyplot.data  <- rep.data %>% 
  filter(valid != "drop" & trial != "NA") %>% 
  group_by(study, title, condition, subid, agey, aged) %>%
  arrange(condition, subid, agey, aged) %>%
  summarise("correct" = round(mean(correct)*100, 2),
            "trials" = length(valid))

difficulty.plot <- ggplot(rep_difficultyplot.data, 
                    aes(x=reorder(condition, -correct), y=correct, colour = condition)) +
  geom_hline(yintercept=50, linetype="dashed", color = "black") +
  geom_boxplot() +
  geom_jitter() +
  theme_minimal() +
  theme(legend.position = "none")

difficulty.plot

```














