---
title: "Reste"
output: html_document
date: "2025-04-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

## Including Plots

```{r rep_s1_bayes_predata, echo = FALSE, include=F, eval=T, results='asis'}

# table(rep.data$study, rep.data$condition)

# prepare data 
rep.S1.bayes.data  <- rep.data %>%
  filter(valid != "drop") %>% # valid participants only 
  filter(study == "study1") %>% # in study one
  filter(trial != "fam") %>% 
  select(condition, subid, sex, aged, correct, trial, rt) %>%
  mutate(condition = factor(condition, levels = c(
        "Representation", # first level becomes reference
        "Pars Pro Toto", 
        "Simple Form Analogy", 
        "Complex Form Analogy"))) %>%  
  mutate(sex = factor(sex, levels = c(
        "0", # first level becomes reference
        "1"))) %>%  
  mutate(z.trial = scale(as.numeric(trial)),
         ageinyears = aged/365.25, 
         z.age = ageinyears - mean(ageinyears),
         z.sex = scale(as.numeric(sex)))

# clean data set?
# str(rep.S1.bayes.data) # overview
# sapply(rep.S1.bayes.data, function(x) sum(is.na(x)))

```


```{r s2_bayes_prep_data, echo = FALSE, include=T, eval=T, results='asis'}

# prepare data 
rep.S2.bayes.data  <- rep.data %>%
  filter(valid != "drop") %>% # valid participants only 
  filter(study == "study2") %>% # in study one
  filter(trial != "fam") %>% 
  select(condition, subid, sex, aged, correct, trial) %>%
  mutate(condition = factor(condition, levels = c(
        "Absolute Position", # first level becomes reference
        "Relative Position", 
        "Orientation of Object", 
        "Orientation of Feature"))) %>%  
  mutate(sex = factor(sex, levels = c(
        "0", # first level becomes reference
        "1"))) %>%  
  mutate(z.trial = scale(as.numeric(trial)),
         ageinyears = aged/365.25, 
         z.age = ageinyears - mean(ageinyears),
         z.sex = scale(as.numeric(sex)))

 
# # prepare data 
# rep.S2.bayes.data  <- rep.data %>%
#   filter(valid != "drop") %>% # valid participants only 
#   filter(study == "study2") %>% # in study 2
#   filter(trial != "fam") %>%
#   select(condition, subid, sex, ageinyears, correct, trial) %>%
#   mutate(z.trial = scale(as.numeric(as.character(trial))),
#          z.age = agey - mean(agey),
#          z.sex = scale(as.numeric(sex)),
#          subid = paste0("id", subid))%>%
#   mutate(condition = as.character(condition))

```


```{r s3_bayes_prep_data, echo = FALSE, include=T, eval=T, results='asis'}

# prepare data 
rep.S3.bayes.data  <- rep.data %>%
  filter(valid != "drop") %>% # valid participants only 
  filter(study == "study3") %>% # in study3
  filter(trial != "fam") %>% 
  select(condition, subid, sex, aged, correct, trial, rt) %>%
  mutate(condition = factor(condition, levels = c(
        "Size of Object", # first level becomes reference
        "Size of Feature", 
        "Number of Object", 
        "Number of Feature"))) %>%  
  mutate(sex = factor(sex, levels = c(
        "0", # first level becomes reference
        "1"))) %>%  

  mutate(z.trial = scale(as.numeric(trial)),
         ageinyears = aged/365.25, 
         z.age = ageinyears - mean(ageinyears),
         z.sex = scale(as.numeric(sex)))

```

