---
title: "Statcheck_writeup"
output: word_document
date: "2026-03-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load}


# # 
# # t(15) = 4.00, p = .001.
# 
# study1_check <- rep.s1.freq %>% 
#   mutate(reporting_text =
#            
#            paste0("for the ",
#                  Age,
#                  "(", Condition, ")",
#                  " we found a result (t(", 
#                  df,
#                  ") = ",
#                  `t(N-1)`,
#                  ", p = ",
#                  p , ")"
#                  )
#          )
# 
# study2_check <- rep.s2.freq %>% 
#   mutate(reporting_text =
#            
#            paste0("for the ",
#                   Age,
#                   " we found a result (t(", 
#                   df,
#                   ") = ",
#                   `t(N-1)`,
#                   ", p = ",
#                   p , ")"
#            )
#   )
# 
# study3_check <- rep.s3.freq %>% 
#   mutate(reporting_text =
#            
#            paste0("for the ",
#                   Age,
#                   " we found a result (t(", 
#                   df,
#                   ") = ",
#                   `t(N-1)`,
#                   ", p = ",
#                   p , ")"
#            )
#   )
# 
# 
# final_check <- rbind(study1_check, study2_check, study3_check)
# 
# 
# 
# final_check$reporting_text
# 
#write_rds(final_check, "./finalcheck.rds")

library(tidyverse)
final_check<- read_rds("./finalcheck.rds")


```


Here we report that

`r final_check$reporting_text` 


