---
title: "manuscript_main_Reste"
output: pdf_document
date: "2025-09-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


<!-- RESTE ...Backup von alten Versionen -->

```{r rep_S1_bayes_fullmodel_plotting_sketch, echo=FALSE, eval=F, warning = F, message=F}
# packages -----------
# library(patchwork)
# library(magick)
# library(grid)
# library(ggplotify)
# library(dplyr)
# library(ggplot2)
# library(magick)

library(cowplot)

# creating plots -------------------------------------

# Get the selected condition level
this_condition <- levels(d1$condition)[1]
# Create the plot
plot_1 <- ggplot() +
  geom_hline(yintercept = .5, lty = 2, alpha = .75) +
  
  geom_point(data = d1 %>% filter(condition == this_condition), 
             aes(x = ageinyears, y = mean, col = I(colour)), alpha = .5, shape = 1) +
  
  geom_smooth(data = f1 %>% filter(condition == this_condition),
              aes(x = age, y = Estimate, ymin = Q2.5, ymax = Q97.5, 
                  fill = I(colour), col = I(colour)),
              stat = "identity", alpha = .25) +
  
  geom_point(data = p1 %>% filter(condition == this_condition),
             aes(x = days/365.25, y = .5, fill = I(colour), col = I(colour)), 
             stat = "identity", size = 3) +
  
  geom_text(data = p1 %>% filter(condition == this_condition),
            aes(label = months, x = days/365.25, y = .24, 
                fill = I(colour), col = I(colour)), 
            angle = 90, size = 4, parse = TRUE) +
  
  geom_text(data = p1 %>% filter(condition == this_condition),
            aes(label = "months", x = days/365.25, y = .38, 
                fill = I(colour), col = I(colour)), 
            angle = 90, size = 4, parse = TRUE) +
  theme_minimal() +
  ylim(0, 1) +
  xlim(3, 7) +
  labs(y = "Proportion Correct") +
  theme(
    # axis.title.y = element_blank(),
    axis.title.x = element_blank(),
    # axis.text.y = element_blank(),
    legend.position = "none")

# Get the selected condition level
this_condition <- levels(d1$condition)[2]
# Create the plot
plot_2 <- ggplot() +
  geom_hline(yintercept = .5, lty = 2, alpha = .75) +
  
  geom_point(data = d1 %>% filter(condition == this_condition), 
             aes(x = ageinyears, y = mean, col = I(colour)), alpha = .5, shape = 1) +
  
  geom_smooth(data = f1 %>% filter(condition == this_condition),
              aes(x = age, y = Estimate, ymin = Q2.5, ymax = Q97.5, 
                  fill = I(colour), col = I(colour)),
              stat = "identity", alpha = .25) +
  
  geom_point(data = p1 %>% filter(condition == this_condition),
             aes(x = days/365.25, y = .5, fill = I(colour), col = I(colour)), 
             stat = "identity", size = 3) +
  
  geom_text(data = p1 %>% filter(condition == this_condition),
            aes(label = months, x = days/365.25, y = .24, 
                fill = I(colour), col = I(colour)), 
            angle = 90, size = 4, parse = TRUE) +
  
  geom_text(data = p1 %>% filter(condition == this_condition),
            aes(label = "months", x = days/365.25, y = .38, 
                fill = I(colour), col = I(colour)), 
            angle = 90, size = 4, parse = TRUE) +
  theme_minimal() +
  ylim(0, 1) +
  xlim(3, 7) +
  theme(
    axis.title.y = element_blank(),
    axis.title.x = element_blank(),
    axis.text.y = element_blank(),
    legend.position = "none")

# Get the selected condition level
this_condition <- levels(d1$condition)[3]
# Create the plot
plot_3 <- ggplot() +
  geom_hline(yintercept = .5, lty = 2, alpha = .75) +
  
  geom_point(data = d1 %>% filter(condition == this_condition), 
             aes(x = ageinyears, y = mean, col = I(colour)), alpha = .5, shape = 1) +
  
  geom_smooth(data = f1 %>% filter(condition == this_condition),
              aes(x = age, y = Estimate, ymin = Q2.5, ymax = Q97.5, 
                  fill = I(colour), col = I(colour)),
              stat = "identity", alpha = .25) +
  
  geom_point(data = p1 %>% filter(condition == this_condition),
             aes(x = days/365.25, y = .5, fill = I(colour), col = I(colour)), 
             stat = "identity", size = 3) +
  
  geom_text(data = p1 %>% filter(condition == this_condition),
            aes(label = months, x = days/365.25, y = .24, 
                fill = I(colour), col = I(colour)), 
            angle = 90, size = 4, parse = TRUE) +
  
  geom_text(data = p1 %>% filter(condition == this_condition),
            aes(label = "months", x = days/365.25, y = .38, 
                fill = I(colour), col = I(colour)), 
            angle = 90, size = 4, parse = TRUE) +
  theme_minimal() +
  ylim(0, 1) +
  xlim(3, 7) +
  theme(
    axis.title.y = element_blank(),
    axis.title.x = element_blank(),
    axis.text.y = element_blank(),
    legend.position = "none")



# Get the selected condition level
this_condition <- levels(d1$condition)[4]
# Create the plot
plot_4 <- ggplot() +
  geom_hline(yintercept = .5, lty = 2, alpha = .75) +
  
  geom_point(data = d1 %>% filter(condition == this_condition), 
             aes(x = ageinyears, y = mean, col = I(colour)), alpha = .5, shape = 1) +
  
  geom_smooth(data = f1 %>% filter(condition == this_condition),
              aes(x = age, y = Estimate, ymin = Q2.5, ymax = Q97.5, 
                  fill = I(colour), col = I(colour)),
              stat = "identity", alpha = .25) +
  
  geom_point(data = p1 %>% filter(condition == this_condition),
             aes(x = days/365.25, y = .5, fill = I(colour), col = I(colour)), 
             stat = "identity", size = 3) +
  
  geom_text(data = p1 %>% filter(condition == this_condition),
            aes(label = months, x = days/365.25, y = .24, 
                fill = I(colour), col = I(colour)), 
            angle = 90, size = 4, parse = TRUE) +
  
  geom_text(data = p1 %>% filter(condition == this_condition),
            aes(label = "months", x = days/365.25, y = .38, 
                fill = I(colour), col = I(colour)), 
            angle = 90, size = 4, parse = TRUE) +
  theme_minimal() +
  ylim(0, 1) +
  xlim(3, 7) +
  theme(
    axis.title.y = element_blank(),
    axis.title.x = element_blank(),
    axis.text.y = element_blank(),
    legend.position = "none")

# loading images ---------------

image_1  <- image_read(paste0("../illustrations/plotexample ", levels(d1$condition)[1], ".png")) 
image_2 <- image_read(paste0("../illustrations/plotexample ", levels(d1$condition)[2], ".png")) 
image_3 <- image_read(paste0("../illustrations/plotexample ", levels(d1$condition)[3], ".png")) 
image_4 <- image_read(paste0("../illustrations/plotexample ", levels(d1$condition)[4], ".png")) 


# combining things -----------

plots_1234 <- plot_grid(plot_1, plot_2, plot_3, plot_4,
                        nrow =1, align = 'h')
plot_S1 <- ggdraw() + 
  draw_plot(plots_1234, 0, 0, 1, 0.75) +  # Plot takes lower 80% of canvas
  
  draw_image(image_1, x = 0.03, y = 0.6, width = 0.22, height = 0.4) +
  draw_image(image_2, x = .265, y = 0.6, width = 0.22, height = 0.4) +
  draw_image(image_3, x = .513, y = 0.6, width = 0.22, height = 0.4) +
  draw_image(image_4, x = .762, y = 0.6, width = 0.22, height = 0.4) +  
  
  draw_label(levels(d1$condition)[1], x = 0.147, y = .94, fontface = "bold", size = 14, hjust = 0.5) +
  draw_label(levels(d1$condition)[2], x = 0.375, y = .94, fontface = "bold", size = 14, hjust = 0.5) +
  draw_label(levels(d1$condition)[3], x = 0.632, y = .94, fontface = "bold", size = 14, hjust = 0.5) +
  draw_label(levels(d1$condition)[4], x = 0.88, y = .94, fontface = "bold", size = 14, hjust = 0.5)

plot_S1


```

```{r rep_S1_bayes_fullmodel_plotting_new2904, echo=FALSE, eval=F, warning = F, message=F}

# library(ggplot2)
library(png)
library(grid)
# while (!is.null(dev.list())) dev.off()

# main plot -----
# library(ggplot2)
# library(png)
library(grid)
# while (!is.null(dev.list())) dev.off()

# Step 1: Load the image file (PNG)
img <- readPNG("../illustrations/plotexample Pars pro Toto.png")
img_grob <- rasterGrob(img, interpolate = TRUE)

# Step 2: Create main plot
main_plot <- ggplot() +
  geom_hline(yintercept = 0.5, linetype = "dashed", color = "grey70", alpha = 0.75) +
  
  geom_point(data = d1, aes(x = ageinyears, y = mean, colour = colour), alpha = 0.5, shape = 1, size = 2) +
  
  geom_smooth(data = f1, aes(x = age, y = Estimate, ymin = Q2.5, ymax = Q97.5, fill = colour, colour = colour),
              stat = "identity", alpha = 0.2, linewidth = 0.8) +
  
  geom_point(data = p1, aes(x = days/365.25, y = 0.5, fill = colour, colour = colour), size = 4, shape = 21, stroke = 1) +
  geom_point(data = p1, aes(x = days/365.25, y = 0.5, fill = "black", colour = "black"), size = 0.5, shape = 21, stroke = 1) +
  geom_text(data = p1, aes(label = months, x = days/365.25, y = 0.24, colour = "black"),
            angle = 90, size = 3.2, vjust = 0.5) +
  
  geom_text(data = p1, aes(label = "months", x = days/365.25, y = 0.38, colour = "black"), 
            angle = 90, size = 3.2, vjust = 0.5) +
  
  scale_colour_identity() +
  scale_fill_identity() +
  scale_y_continuous(labels = function(x) paste0(x*100, "%")) + # Multiply by 100 & add %  
  
  
  facet_grid(cols = vars(condition)) +
  
  labs(x = "Age", y = "Proportion correct") +
  
  coord_cartesian(ylim = c(0, 1), xlim = c(2.7, 7.3)) +   # Allow more Y space for image
  
  theme_minimal(base_size = 13) +
  theme(
    panel.border = element_rect(colour = "grey30", fill = NA, size = 0.8),
    strip.background = element_rect(colour = "grey30", size = 0.8),
    strip.text = element_text(face = "bold", size = rel(0.8), 
                              margin = margin(t = 5, b = 45)),
    strip.switch.pad.grid = unit(0, "cm"),
    axis.title = element_text(face = "bold", size = rel(0.8)),
    axis.text = element_text(size = rel(0.8)),
    legend.position = "none",
    panel.grid.minor = element_blank()
  )

# adding images -----
# load images
image_1 <- image_read(paste0("../illustrations/plotexample ", levels(d1$condition)[1], ".png")) 
image_2 <- image_read(paste0("../illustrations/plotexample ", levels(d1$condition)[2], ".png")) 
image_3 <- image_read(paste0("../illustrations/plotexample ", levels(d1$condition)[3], ".png")) 
image_4 <- image_read(paste0("../illustrations/plotexample ", levels(d1$condition)[4], ".png")) 
# create grobs
image_1_grob <- rasterGrob(image_1, interpolate = TRUE)
image_2_grob <- rasterGrob(image_2, interpolate = TRUE)
image_3_grob <- rasterGrob(image_3, interpolate = TRUE)
image_4_grob <- rasterGrob(image_4, interpolate = TRUE)


# place images on the plot
library(cowplot)

final_plot <- ggdraw(main_plot) +
  draw_grob(image_1_grob, x = 0.08, y = 0.78, width = 0.23, height = 0.13) +
  draw_grob(image_2_grob, x = 0.31, y = 0.78, width = 0.23, height = 0.13) +
  draw_grob(image_3_grob, x = 0.54, y = 0.78, width = 0.23, height = 0.13) +
  draw_grob(image_4_grob, x = 0.77, y = 0.78, width = 0.23, height = 0.13)

# Save  ------------
ggsave(
  filename = "../illustrations/final_plot.png",
  plot = final_plot,   # <- IMPORTANT: plot = main_plot
  device = "png",
  width = 8, height = 4,
  dpi = 300,
  units = "in",
  bg = "white"
)

# display plot
img <- image_read("../illustrations/study1_plot.png")

windows(width = 15, height = 10)  # On Windows
plot(img)

```

```{r rep_S1_bayes_fullmodel_plotting, echo=FALSE, eval=F, warning = F, message=F}


# side by side
ggplot()+
  geom_hline(yintercept = .5, lty = 2, alpha = .75)+
  geom_point(data = d1, aes(x = ageinyears, y = mean, col = condition), alpha = .5, shape = 1)+
  geom_smooth(data = f1, aes(x = age, y = Estimate, ymin = Q2.5, ymax = Q97.5, fill = condition, col = condition),
              stat = "identity", alpha = .25)+
  geom_point(data = p1, aes(x = days/365.25, y = .5, fill = condition, col = condition), stat = "identity", size = 3)+
  geom_text(data = p1, aes(label = months, x = days/365.25, y = .24, fill = condition, col = condition), angle = 90, size = 4, parse = TRUE)+
  geom_text(data = p1, aes(label = "months", x = days/365.25, y = .38, fill = condition, col = condition), angle = 90, size = 4, parse = TRUE)+
  theme_minimal()+
  scale_color_ptol(name = "condition")+
  scale_fill_ptol(name = "condition")+
  facet_grid(cols = vars(condition))+
  labs(x = "Age", y = "Proportion correct")+
  ylim(0, 1)+
  xlim(3, 7)+
  theme(legend.position = "bottom")
```

```{r S2_bayes_fullmodel, echo=FALSE, include=F, eval=F}


# S2.full.bm<-brm(correct~condition+z.age+(1|subid), 
#                data=rep.S2.bayes.data, 
#                family=bernoulli(),
#                chains = 4,
#                iter= 2000,
#                cores= 4)
# 

S2.null.bm<-brm(correct~condition+z.age+z.trial+z.sex+(z.trial|subid), 
               data= rep.S2.bayes.data, 
               family=bernoulli(),
               chains = 4,
               iter= 5000,
               cores= 4)

S2.null.bm <- add_criterion(S2.null.bm, c("loo", "waic"))

S2.full.bm<-brm(correct~condition*z.age+z.trial+z.sex+(z.trial|subid), 
               data= rep.S2.bayes.data, 
               family=bernoulli(),
               chains = 4,
               iter= 5000,
               cores= 4)

S2.full.bm <- add_criterion(S2.full.bm, c("loo", "waic"))

S2.comp <- loo_compare(S2.null.bm, S2.full.bm, criterion = "waic")%>%as_tibble(rownames = "index")
S2.weights <- model_weights(S2.null.bm, S2.full.bm, criterion = "waic") %>% as_tibble(rownames = "index")

# 
# loo_compare(S2.null.bm, S2.full.bm, criterion = "waic")%>%as_tibble(rownames = "index")
# model_weights(S2.null.bm, S2.full.bm, criterion = "waic")

# Saving the model (to not rerun it every time)

### LOO COMPARISON
### not reported, essentially identical
# S2.null.loo <- loo(S2.null.bm)
# S2.full.loo <- loo(S2.full.bm)
# S2.loo.comp <- loo_compare(S2.null.loo, S2.full.loo) %>%
#   as_tibble(rownames = "model")
# S2.loo.comp

# Saving the model (to not rerun it every time)
saveRDS(S2.full.bm, "../models/S2.full.bm.rds")
saveRDS(S2.null.bm, "../models/S2.null.bm.rds")
saveRDS(S2.comp, "../models/S2.comp.rds")
saveRDS(S2.weights, "../models/S2.weights.rds")





```

```{r S2_bayes_fullmodel_prep_prepplotting, echo=FALSE, eval=F}

# load model from saving rds
S2.full.bm <- readRDS("../models/S2.full.bm.rds")

nd2 <- tibble(z.age = rep(seq(from = min(rep.S2.bayes.data$z.age), 
                              to = max(rep.S2.bayes.data$z.age), 
                              length.out = 50),4),
             condition = c(rep("Relative Position",50), 
                           rep("Absolute Position",50), 
                           rep("Orientation of Feature",50), 
                           rep("Orientation of Object",50)), # the four conditions in the data
             z.sex = rep(0,200),
             z.trial = rep(0,200))

f2 <- fitted(S2.full.bm, 
             newdata = nd2, 
             re_formula = NA) %>% 
  # this tells the function to ignore the random effects - in theory, we could generate predictions for specific individuals
  as_tibble() %>%
  bind_cols(nd2)%>%
  mutate(age = z.age + mean(rep.S2.bayes.data$ageinyears)) # convert age back to the original scale by adding the mean of the data


# summarize the data to include them in the plot later on
d2 <- rep.S2.bayes.data%>%
  group_by(subid, ageinyears, condition)%>%
  summarise(mean = mean(correct))

```

```{r S3_bayes_fullmodel, echo=FALSE, include=F, eval=F}


S3.null.bm<-brm(correct~condition+z.age+z.trial+z.sex+(z.trial|subid), 
               data= rep.S3.bayes.data, 
               family=bernoulli(),
               chains = 4,
               iter= 5000,
               cores= 4)

S3.null.bm <- add_criterion(S3.null.bm, c("loo", "waic"))

S3.full.bm<-brm(correct~condition*z.age+z.trial+z.sex+(z.trial|subid), 
               data= rep.S3.bayes.data, 
               family=bernoulli(),
               chains = 4,
               iter= 5000,
               cores= 4)

S3.full.bm <- add_criterion(S3.full.bm, c("loo", "waic"))

S3.comp <- loo_compare(S3.null.bm, S3.full.bm, criterion = "waic")%>%as_tibble(rownames = "index")
S3.weights <- model_weights(S3.null.bm, S3.full.bm, criterion = "waic") %>% as_tibble(rownames = "index")

### LOO COMPARISON
### not reported, essentially identical
# S2.null.loo <- loo(S2.null.bm)
# S2.full.loo <- loo(S2.full.bm)
# S2.loo.comp <- loo_compare(S2.null.loo, S2.full.loo) %>%
#   as_tibble(rownames = "model")
# S2.loo.comp

# Saving the model (to not rerun it every time)
saveRDS(S3.full.bm, "../models/S3.full.bm.rds")
saveRDS(S3.null.bm, "../models/S3.null.bm.rds")
saveRDS(S3.comp, "../models/S3.comp.rds")
saveRDS(S3.weights, "../models/S3.weights.rds")

# preregistered: correct ~ task*z.age +z.trial +z.sex +(z.trial|id)
# 
# S3.full.bm<-brm(correct~condition*z.age+z.trial+z.sex+(z.trial|subid), 
#                 data= rep.S3.bayes.data, 
#                 family=bernoulli(),
#                 chains = 4,
#                 iter= 2000,
#                 cores= 4)
# 
# S3.full.bm <- add_criterion(S3.full.bm, c("loo", "waic"))
# 
# # Saving the model (to not rerun it every time)
# saveRDS(S3.full.bm, "../models/S3.full.bm.rds")

```

```{r S3_bayes_fullmodel_prep_prepplotting, echo=FALSE, eval=F, warning=F, message=F}

# load model from saving rds
S3.full.bm <- readRDS("../models/S3.full.bm.rds")

nd3 <- tibble(z.age = rep(seq(from = min(rep.S3.bayes.data$z.age), 
                              to = max(rep.S3.bayes.data$z.age), 
                              length.out = 50),4),
             condition = c(rep("Number of Object",50), 
                           rep("Number of Feature",50), 
                           rep("Size of Object",50), 
                           rep("Size of Feature",50)),
             z.sex = rep(0,200),
             z.trial = rep(0,200))

f3 <- fitted(S3.full.bm, 
             newdata = nd3, 
             re_formula = NA) %>% 
  as_tibble() %>%
  bind_cols(nd3)%>%
  mutate(age = z.age + mean(rep.S3.bayes.data$ageinyears)) 


# summarize the data to include them in the plot later on
d3 <- rep.S3.bayes.data%>%
  group_by(subid, ageinyears, condition)%>%
  summarise(mean = mean(correct)) 

```

```{r S1_bayes_plot_no_facets, echo=FALSE, eval=F, warning = F, message=F}

# Plot without facetting

ggplot()+
  geom_hline(yintercept = .5, lty = 2, alpha = .75)+
  geom_point(data = d1, aes(x = ageinyears, y = mean, col = condition), alpha = .5, shape = 1)+
  geom_smooth(data = f1, aes(x = age, y = Estimate, ymin = Q2.5, ymax = Q97.5, fill =condition, col = condition), 
              stat = "identity", alpha = .25)+
  geom_point(data=p1, aes(x = days/365.25, y = .5, fill = condition, col = condition), stat = "identity", size=3)+
  geom_text(data=p1, aes(label = months, x = days/365.25, y = .24, fill = condition, col = condition), angle=90, size = 4, parse=T)+
  geom_text(data=p1, aes(label = "months", x = days/365.25, y = .38, fill = condition, col = condition), angle=90, size = 4, parse=T)+
  theme_minimal()+
  scale_color_ptol(name = "condition")+
  scale_fill_ptol(name = "condition")+
  #facet_grid(~condition)+
  labs(x = "Age", y="Proportion correct")+
  ylim(0,1)+
  xlim(3,7)+
  theme(legend.position = "bottom")



```

```{r S1_bayes_plot, echo=FALSE, eval=F, warning = F, message=F}

p1 <- f1 %>%
  mutate(age = age * 365.25)%>%
  group_by(condition)%>%
  summarise(
    Q2.5_closest_to.5 = Q2.5[which.min(abs(Q2.5-.5))],
    estimate_closest_to.5 = Estimate[which.min(abs(Q2.5-.5))],
    days = age[which.min(abs(Q2.5-.5))],
    months = round(days/30.5),
    years = round(days/365.25, 2),
    monthlabels = as.character(paste(months, "months"))
    )

S1_plot <- ggplot()+
  geom_hline(yintercept = .5, lty = 2, alpha = .75)+
  geom_point(data = d1, aes(x = ageinyears, y = mean, col = condition), alpha = .5, shape = 1)+
  geom_smooth(data = f1, aes(x = age, y = Estimate, ymin = Q2.5, ymax = Q97.5, fill =condition, col = condition), 
              stat = "identity", alpha = .25)+
  geom_point(data=p1, aes(x = days/365.25, y = .5, fill = condition, col = condition), stat = "identity", size=3)+
  geom_text(data=p1, aes(label = months, x = days/365.25, y = .24, fill = condition, col = condition), angle=90, size = 4, parse=T)+
  geom_text(data=p1, aes(label = "months", x = days/365.25, y = .38, fill = condition, col = condition), angle=90, size = 4, parse=T)+
  theme_minimal()+
  scale_color_ptol(name = "condition")+
  scale_fill_ptol(name = "condition")+
  facet_grid(~condition)+
  labs(x = "Age", y="Proportion correct")+
  ylim(0,1)+
  xlim(3,7)+
  theme(legend.position = "bottom")

#
S1_plot

```

```{r S2_bayes_plot, echo=FALSE, eval=F, warning=F, message=F}

p2 <- f2 %>%
  mutate(age = age * 365.25)%>%
  group_by(condition)%>%
  summarise(
    Q2.5_closest_to.5 = Q2.5[which.min(abs(Q2.5-.5))],
    estimate_closest_to.5 = Estimate[which.min(abs(Q2.5-.5))],
    days = age[which.min(abs(Q2.5-.5))],
    months = round(days/30.5),
    years = round(days/365.25, 2),
    monthlabels = as.character(paste(months, "months"))
  )

ggplot()+
  geom_hline(yintercept = .5, lty = 2, alpha = .75)+
  geom_point(data = d2, aes(x = ageinyears, y = mean, col = condition), alpha = .5, shape = 1)+
  geom_smooth(data = f2, aes(x = age, y = Estimate, ymin = Q2.5, ymax = Q97.5, fill =condition, col = condition), 
              stat = "identity", alpha = .25)+
  geom_point(data=p2, aes(x = days/365.25, y = .5, fill = condition, col = condition), stat = "identity", size=3)+
  geom_text(data=p2, aes(label = months, x = days/365.25, y = .24, fill = condition, col = condition), angle=90, size = 4, parse=T)+
  geom_text(data=p2, aes(label = "months", x = days/365.25, y = .38, fill = condition, col = condition), angle=90, size = 4, parse=T)+
  theme_minimal()+
  scale_color_ptol(name = "condition")+
  scale_fill_ptol(name = "condition")+
  #facet_grid(~condition)+
  labs(x = "Age", y="Proportion correct")+
  ylim(0,1)+
  xlim(3,7)+
  theme(legend.position = "bottom")

```

```{r S2_mixbayes_plot, echo=FALSE, eval=F, warning=F, message=F}


p2 <- f2 %>%
  mutate(age = age * 365.25)%>%
  group_by(condition)%>%
  summarise(
    Q2.5_closest_to.5 = Q2.5[which.min(abs(Q2.5-.5))],
    estimate_closest_to.5 = Estimate[which.min(abs(Q2.5-.5))],
    days = age[which.min(abs(Q2.5-.5))],
    months = round(days/30.5),
    years = round(days/365.25, 2),
    monthlabels = as.character(paste(months, "months"))
  )

ggplot()+
  geom_hline(yintercept = .5, lty = 2, alpha = .75)+
  geom_point(data = d2, aes(x = ageinyears, y = mean, col = condition), alpha = .5, shape = 1)+
  geom_smooth(data = f2, aes(x = age, y = Estimate, ymin = Q2.5, ymax = Q97.5, fill =condition, col = condition), 
              stat = "identity", alpha = .25)+
  geom_point(data=p2, aes(x = days/365.25, y = .5, fill = condition, col = condition), stat = "identity", size=3)+
  geom_text(data=p2, aes(label = months, x = days/365.25, y = .24, fill = condition, col = condition), angle=90, size = 4, parse=T)+
  geom_text(data=p2, aes(label = "months", x = days/365.25, y = .38, fill = condition, col = condition), angle=90, size = 4, parse=T)+
  theme_minimal()+
  scale_color_ptol(name = "condition")+
  scale_fill_ptol(name = "condition")+
  facet_grid(~condition)+
  labs(x = "Age", y="Proportion correct")+
  ylim(0,1)+
  xlim(3,7)+
  theme(legend.position = "bottom")

```

```{r S3_bayes_plot, echo=FALSE, eval=F, warning=F, message=F}

# Plot without facetting
p3 <- f3 %>%
  mutate(age = age * 365.25)%>%
  group_by(condition)%>%
  summarise(
    Q2.5_closest_to.5 = Q2.5[which.min(abs(Q2.5-.5))],
    estimate_closest_to.5 = Estimate[which.min(abs(Q2.5-.5))],
    days = age[which.min(abs(Q2.5-.5))],
    months = round(days/30.5),
    years = round(days/365.25, 2),
    monthlabels = as.character(paste(months, "months")))

ggplot()+
  geom_hline(yintercept = .5, lty = 2, alpha = .75)+
  geom_point(data = d3, aes(x = ageinyears, y = mean, col = condition), alpha = .5, shape = 1)+
  geom_smooth(data = f3, aes(x = age, y = Estimate, ymin = Q2.5, ymax = Q97.5, fill =condition, col = condition), 
              stat = "identity", alpha = .25)+
  geom_point(data=p3, aes(x = days/365.25, y = .5, fill = condition, col = condition), stat = "identity", size=3)+
  geom_text(data=p3, aes(label = months, x = days/365.25, y = .24, fill = condition, col = condition), angle=90, size = 4, parse=T)+
  geom_text(data=p3, aes(label = "months", x = days/365.25, y = .38, fill = condition, col = condition), angle=90, size = 4, parse=T)+
  theme_minimal()+
  scale_color_ptol(name = "condition")+
  scale_fill_ptol(name = "condition")+
  #facet_grid(~condition)+
  labs(x = "Age", y="Proportion correct")+
  ylim(0,1)+
  xlim(3,7)+
  theme(legend.position = "bottom")




```

```{r S3_mixbayes_plot, echo=FALSE, eval=F, warning=F, message=F}

p3 <- f3 %>%
  mutate(age = age * 365.25)%>%
  group_by(condition)%>%
  summarise(
    Q2.5_closest_to.5 = Q2.5[which.min(abs(Q2.5-.5))],
    estimate_closest_to.5 = Estimate[which.min(abs(Q2.5-.5))],
    days = age[which.min(abs(Q2.5-.5))],
    months = round(days/30.5),
    years = round(days/365.25, 2),
    monthlabels = as.character(paste(months, "months")))

ggplot()+
  geom_hline(yintercept = .5, lty = 2, alpha = .75)+
  geom_point(data = d3, aes(x = ageinyears, y = mean, col = condition), alpha = .5, shape = 1)+
  geom_smooth(data = f3, aes(x = age, y = Estimate, ymin = Q2.5, ymax = Q97.5, fill =condition, col = condition), 
              stat = "identity", alpha = .25)+
  geom_point(data=p3, aes(x = days/365.25, y = .5, fill = condition, col = condition), stat = "identity", size=3)+
  geom_text(data=p3, aes(label = months, x = days/365.25, y = .24, fill = condition, col = condition), angle=90, size = 4, parse=T)+
  geom_text(data=p3, aes(label = "months", x = days/365.25, y = .38, fill = condition, col = condition), angle=90, size = 4, parse=T)+
  theme_minimal()+
  scale_color_ptol(name = "condition")+
  scale_fill_ptol(name = "condition")+
  facet_grid(~condition)+
  labs(x = "Age", y="Proportion correct")+
  ylim(0,1)+
  xlim(3,7)+
  theme(legend.position = "bottom")



```

<!-- RESTE ...Backup von alten Versionen -->