---
title: "Plotting Reste"
output: html_document
date: "2025-09-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



<!-- Plotting ohne stimuli -->

```{r rep_S1_bayes_fullmodel_plotting_new, echo=FALSE, eval=F, warning = F, message=F}

# place images on the plot
# while (!is.null(dev.list())) dev.off()


# Create main plot
main_plot <- ggplot() +
  geom_hline(yintercept = 0.5, linetype = "dashed", color = "grey70", alpha = 0.75) +
  
  geom_point(data = d1, aes(x = ageinyears, y = mean, colour = colour), alpha = 0.5, shape = 1, size = 2) +
  
  geom_smooth(data = f1, aes(x = age, y = Estimate, ymin = Q2.5, ymax = Q97.5, fill = colour, colour = colour),
              stat = "identity", alpha = 0.2, linewidth = 0.8) +
  
  geom_point(data = p1, aes(x = days/365.25, y = 0.5, fill = colour, colour = colour), size = 4, shape = 21, stroke = 1) +
  geom_point(data = p1, aes(x = days/365.25, y = 0.5, fill = "black", colour = "black"), size = 0.5, shape = 21, stroke = 1) +
  geom_text(data = p1, aes(label = months, x = days/365.25, y = 0.13, colour = "black", fontface = "bold"),
            angle = 90, size = 3.2, vjust = 0.5) +
  
  geom_text(data = p1, aes(label = "months", x = days/365.25, y = .31, colour = "black", fontface = "bold"), 
            angle = 90, size = 3.2, vjust = 0.5) +
  
  scale_colour_identity() +
  scale_fill_identity() +
  scale_y_continuous(labels = function(x) paste0(x*100, "%")) + # Multiply by 100 & add %  
  
  
  facet_grid(cols = vars(condition)) +
  
  labs(x = "Age", y = "Proportion Correct") +
  
  coord_cartesian(ylim = c(0, 1), xlim = c(2.7, 7.3)) +   # Allow more Y space for image
  
  theme_minimal(base_size = 13) +
  theme(
    panel.border = element_rect(colour = "grey30", fill = NA, size = 1),
    strip.background = element_rect(colour = "grey30", size = 1),
    strip.text = element_text(face = "bold", size = rel(0.8), 
                              margin = margin(t = 5, b = 45)), # HIER STRIPE SPACING via b =
   # strip.switch.pad.grid = unit(0, "cm"),
    axis.title = element_text(face = "bold", size = rel(0.8)),
    axis.text = element_text(size = rel(0.8)),
    legend.position = "none",
    panel.grid.minor = element_blank()
  )

# adding images -----
# load images
image_1 <- image_read(paste0("../illustrations/plotexample ", levels(d1$condition)[1], ".png"))
image_2 <- image_read(paste0("../illustrations/plotexample ", levels(d1$condition)[2], ".png"))
image_3 <- image_read(paste0("../illustrations/plotexample ", levels(d1$condition)[3], ".png"))
image_4 <- image_read(paste0("../illustrations/plotexample ", levels(d1$condition)[4], ".png"))
# create grobs
image_1_grob <- rasterGrob(image_1, interpolate = TRUE)
image_2_grob <- rasterGrob(image_2, interpolate = TRUE)
image_3_grob <- rasterGrob(image_3, interpolate = TRUE)
image_4_grob <- rasterGrob(image_4, interpolate = TRUE)



final_plot <- ggdraw(main_plot) +
  draw_grob(image_1_grob, x = 0.071, y = 0.752, width = 0.25, height = 0.15) +
  draw_grob(image_2_grob, x = 0.3, y = 0.752, width = 0.25, height = 0.15) +
  draw_grob(image_3_grob, x = 0.527, y = 0.752, width = 0.25, height = 0.15) +
  draw_grob(image_4_grob, x = 0.755, y = 0.752, width = 0.25, height = 0.15)

# Save  ------------
ggsave(
  filename = "../illustrations/plot_study1.png",
  plot = final_plot,
  device = "png",
  width = 8, height = 3.5,
  dpi = 300,
  units = "in",
  bg = "white"
)

# # display plot
# img <- image_read("../illustrations/plot_study1.png")
# 
# windows(width = 15, height = 10)  # On Windows
# plot(img)


```

```{r rep_S2_bayes_fullmodel_plotting_new, echo=FALSE, eval=F, warning = F, message=F}

# Create main plot
main_plot <- ggplot() +
  geom_hline(yintercept = 0.5, linetype = "dashed", color = "grey70", alpha = 0.75) +
  
  geom_point(data = d2, aes(x = ageinyears, y = mean, colour = colour), alpha = 0.5, shape = 1, size = 2) +
  
  geom_smooth(data = f2, aes(x = age, y = Estimate, ymin = Q2.5, ymax = Q97.5, fill = colour, colour = colour),
              stat = "identity", alpha = 0.2, linewidth = 0.8) +
  
  geom_point(data = p2, aes(x = days/365.25, y = 0.5, fill = colour, colour = colour), size = 4, shape = 21, stroke = 1) +
  geom_point(data = p2, aes(x = days/365.25, y = 0.5, fill = "black", colour = "black"), size = 0.5, shape = 21, stroke = 1) +
  geom_text(data = p2, aes(label = months, x = days/365.25, y = 0.13, colour = "black", fontface = "bold"),
            angle = 90, size = 3.2, vjust = 0.5) +
  
  geom_text(data = p2, aes(label = "months", x = days/365.25, y = .31, colour = "black", fontface = "bold"), 
            angle = 90, size = 3.2, vjust = 0.5) +
  
  scale_colour_identity() +
  scale_fill_identity() +
  scale_y_continuous(labels = function(x) paste0(x*100, "%")) + # Multiply by 100 & add %  
  
  
  facet_grid(cols = vars(condition)) +
  
  labs(x = "Age", y = "Proportion Correct") +
  
  coord_cartesian(ylim = c(0, 1), xlim = c(2.7, 7.3)) +   # Allow more Y space for image
  
  theme_minimal(base_size = 13) +
  theme(
    panel.border = element_rect(colour = "grey30", fill = NA, size = 1),
    strip.background = element_rect(colour = "grey30", size = 1),
    strip.text = element_text(face = "bold", size = rel(0.8), 
                              margin = margin(t = 5, b = 45)), # HIER STRIPE SPACING via b =
   # strip.switch.pad.grid = unit(0, "cm"),
    axis.title = element_text(face = "bold", size = rel(0.8)),
    axis.text = element_text(size = rel(0.8)),
    legend.position = "none",
    panel.grid.minor = element_blank()
  )

# adding images -----
# load images
image_1 <- image_read(paste0("../illustrations/plotexample ", levels(d2$condition)[1], ".png"))
image_2 <- image_read(paste0("../illustrations/plotexample ", levels(d2$condition)[2], ".png"))
image_3 <- image_read(paste0("../illustrations/plotexample ", levels(d2$condition)[3], ".png"))
image_4 <- image_read(paste0("../illustrations/plotexample ", levels(d2$condition)[4], ".png"))
# create grobs
image_1_grob <- rasterGrob(image_1, interpolate = TRUE)
image_2_grob <- rasterGrob(image_2, interpolate = TRUE)
image_3_grob <- rasterGrob(image_3, interpolate = TRUE)
image_4_grob <- rasterGrob(image_4, interpolate = TRUE)



final_plot <- ggdraw(main_plot) +
  draw_grob(image_1_grob, x = 0.071, y = 0.752, width = 0.25, height = 0.15) +
  draw_grob(image_2_grob, x = 0.3, y = 0.752, width = 0.25, height = 0.15) +
  draw_grob(image_3_grob, x = 0.527, y = 0.752, width = 0.25, height = 0.15) +
  draw_grob(image_4_grob, x = 0.755, y = 0.752, width = 0.25, height = 0.15)

# Save  ------------
ggsave(
  filename = "../illustrations/plot_study2.png",
  plot = final_plot,
  device = "png",
  width = 8, height = 3.5,
  dpi = 300,
  units = "in",
  bg = "white"
)

# # display plot
# img <- image_read("../illustrations/plot_study2.png")
# 
# windows(width = 15, height = 10)  # On Windows
# plot(img)




```

```{r rep_S3_bayes_fullmodel_plotting_new, echo=FALSE, eval=F, warning = F, message=F}


# Create main plot
main_plot <- ggplot() +
  geom_hline(yintercept = 0.5, linetype = "dashed", color = "grey70", alpha = 0.75) +
  
  geom_point(data = d3, aes(x = ageinyears, y = mean, colour = colour), alpha = 0.5, shape = 1, size = 2) +
  
  geom_smooth(data = f3, aes(x = age, y = Estimate, ymin = Q2.5, ymax = Q97.5, fill = colour, colour = colour),
              stat = "identity", alpha = 0.2, linewidth = 0.8) +
  
  geom_point(data = p3, aes(x = days/365.25, y = 0.5, fill = colour, colour = colour), size = 4, shape = 21, stroke = 1) +
  geom_point(data = p3, aes(x = days/365.25, y = 0.5, fill = "black", colour = "black"), size = 0.5, shape = 21, stroke = 1) +
  geom_text(data = p3, aes(label = months, x = days/365.25, y = 0.13, colour = "black", fontface = "bold"),
            angle = 90, size = 3.2, vjust = 0.5) +
  
  geom_text(data = p3, aes(label = "months", x = days/365.25, y = .31, colour = "black", fontface = "bold"), 
            angle = 90, size = 3.2, vjust = 0.5) +
  
  scale_colour_identity() +
  scale_fill_identity() +
  scale_y_continuous(labels = function(x) paste0(x*100, "%")) + # Multiply by 100 & add %  
  
  
  facet_grid(cols = vars(condition)) +
  
  labs(x = "Age", y = "Proportion Correct") +
  
  coord_cartesian(ylim = c(0, 1), xlim = c(2.7, 7.3)) +   # Allow more Y space for image
  
  theme_minimal(base_size = 13) +
  theme(
    panel.border = element_rect(colour = "grey30", fill = NA, size = 1),
    strip.background = element_rect(colour = "grey30", size = 1),
    strip.text = element_text(face = "bold", size = rel(0.8), 
                              margin = margin(t = 5, b = 45)), # HIER STRIPE SPACING via b =
    # strip.switch.pad.grid = unit(0, "cm"),
    axis.title = element_text(face = "bold", size = rel(0.8)),
    axis.text = element_text(size = rel(0.8)),
    legend.position = "none",
    panel.grid.minor = element_blank()
  )

# adding images -----
# load images
image_1 <- image_read(paste0("../illustrations/plotexample ", levels(d3$condition)[1], ".png"))
image_2 <- image_read(paste0("../illustrations/plotexample ", levels(d3$condition)[2], ".png"))
image_3 <- image_read(paste0("../illustrations/plotexample ", levels(d3$condition)[3], ".png"))
image_4 <- image_read(paste0("../illustrations/plotexample ", levels(d3$condition)[4], ".png"))
# create grobs
image_1_grob <- rasterGrob(image_1, interpolate = TRUE)
image_2_grob <- rasterGrob(image_2, interpolate = TRUE)
image_3_grob <- rasterGrob(image_3, interpolate = TRUE)
image_4_grob <- rasterGrob(image_4, interpolate = TRUE)



final_plot <- ggdraw(main_plot) +
  draw_grob(image_1_grob, x = 0.071, y = 0.752, width = 0.25, height = 0.15) +
  draw_grob(image_2_grob, x = 0.3, y = 0.752, width = 0.25, height = 0.15) +
  draw_grob(image_3_grob, x = 0.527, y = 0.752, width = 0.25, height = 0.15) +
  draw_grob(image_4_grob, x = 0.755, y = 0.752, width = 0.25, height = 0.15)

# Save  ------------
ggsave(
  filename = "../illustrations/plot_study3.png",
  plot = final_plot,
  device = "png",
  width = 8, height = 3.5,
  dpi = 300,
  units = "in",
  bg = "white"
)

# # display plot
# img <- image_read("../illustrations/plot_study3.png")
# 
# windows(width = 15, height = 10)  # On Windows
# plot(img)
# 


```





```{r S1_item_intercepts, echo=FALSE, eval=T}

# STUDY 1
S1.item_effects <- ranef(S1.item.model)$item

# Extract random intercepts
S1.item_intercepts <- as_tibble(S1.item_effects[, , "Intercept"], rownames = "item") %>%
  rename(
    estimate = Estimate,
    lower = Q2.5,
    upper = Q97.5) %>% 
  mutate(condition = substr(item,1,4)) %>% 
  mutate(item = substr(item, 10,10)) %>% 
  mutate(condition = case_when(
    condition == "repr" ~ "Representation", 
    condition == "pars" ~ "Pars Pro Toto",
    condition == "fsim" ~"Simple Form Analogy",
    condition == "fcom" ~ "Complex Form Analogy",
    condition == "abpo" ~ "Absolute Position",
    condition == "repo" ~ "Relative Position",
    condition == "orob" ~ "Orientation of Object",
    condition == "orfe" ~ "Orientation of Feature",
    condition == "siob" ~ "Size of Object", 
    condition == "sife" ~ "Size of Feature", 
    condition == "nuob" ~ "Number of Object", 
    condition == "nufe" ~ "Number of Feature",
    TRUE ~ as.character(condition))) %>% 
  mutate(condition = factor(condition, levels = c(
    "Representation", # first level becomes reference
    "Pars Pro Toto", 
    "Simple Form Analogy", 
    "Complex Form Analogy"))) %>% 
  mutate(item = factor(item, levels = c("4", "3", "2", "1")))

S1.item_intercepts <- add_colour(S1.item_intercepts)

S1.item.plot <- ggplot(S1.item_intercepts, aes(x = item, y = estimate)) +
  geom_point(aes(color = I(colour))) +
  geom_errorbar(aes(ymin = lower, ymax = upper, color = I(colour)), width = 0.6, size = .5) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "gray50") +
  coord_flip() +
  facet_wrap(~ condition, scales = "free_y", ncol = 1) +
  labs(
    x = "Item",
    y = "Estimated Deviation from Overall Intercept (log-odds)"
  ) +
  theme_minimal() +
  theme(
    legend.position = "none",  
    strip.text = element_text(size = 10, face = "bold"))

ggsave(
  filename = "../illustrations/plot_study1_item_intercepts.png",
  plot = S1.item.plot,
  device = "png",
  width = 6, height = 4,
  dpi = 300,
  units = "in",
  bg = "white"
)


```

```{r S2_item_intercepts, echo=FALSE, eval=T}

S2.item_effects <- ranef(S2.item.model)$item

# Extract random intercepts
S2.item_intercepts <- as_tibble(S2.item_effects[, , "Intercept"], rownames = "item") %>%
  rename(
    estimate = Estimate,
    lower = Q2.5,
    upper = Q97.5) %>% 
  mutate(condition = substr(item,1,4)) %>% 
  mutate(item = substr(item, 10,10)) %>% 
  mutate(condition = case_when(
    condition == "repr" ~ "Representation", 
    condition == "pars" ~ "Pars Pro Toto",
    condition == "fsim" ~"Simple Form Analogy",
    condition == "fcom" ~ "Complex Form Analogy",
    condition == "abpo" ~ "Absolute Position",
    condition == "repo" ~ "Relative Position",
    condition == "orob" ~ "Orientation of Object",
    condition == "orfe" ~ "Orientation of Feature",
    condition == "siob" ~ "Size of Object", 
    condition == "sife" ~ "Size of Feature", 
    condition == "nuob" ~ "Number of Object", 
    condition == "nufe" ~ "Number of Feature",
    TRUE ~ as.character(condition))) %>% 
  mutate(condition = factor(condition, levels = c(
    "Absolute Position",
    "Relative Position",
    "Orientation of Object",
    "Orientation of Feature"))) %>%
  mutate(item = factor(item, levels = c("4", "3", "2", "1")))

S2.item_intercepts <- add_colour(S2.item_intercepts)

S2.item.plot <- ggplot(S2.item_intercepts, aes(x = item, y = estimate)) +
  geom_point(aes(color = I(colour))) +
  geom_errorbar(aes(ymin = lower, ymax = upper, color = I(colour)), width = 0.6, size = .5) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "gray50") +
  coord_flip() +
  facet_wrap(~ condition, scales = "free_y", ncol = 1) +
  labs(
    x = "Item",
    y = "Estimated Deviation from Overall Intercept (log-odds)"
  ) +
  theme_minimal() +
  theme(
    legend.position = "none",  
    strip.text = element_text(size = 10, face = "bold"))

ggsave(
  filename = "../illustrations/plot_study2_item_intercepts.png",
  plot = S2.item.plot,
  device = "png",
  width = 6, height = 4,
  dpi = 300,
  units = "in",
  bg = "white"
)


```

```{r S3_item_intercepts, echo=FALSE, eval=T}

S3.item_effects <- ranef(S3.item.model)$item

# Extract random intercepts
S3.item_intercepts <- as_tibble(S3.item_effects[, , "Intercept"], rownames = "item") %>%
  rename(
    estimate = Estimate,
    lower = Q2.5,
    upper = Q97.5) %>% 
  mutate(condition = substr(item,1,4)) %>% 
  mutate(item = substr(item, 10,10)) %>% 
  mutate(condition = case_when(
    condition == "repr" ~ "Representation", 
    condition == "pars" ~ "Pars Pro Toto",
    condition == "fsim" ~"Simple Form Analogy",
    condition == "fcom" ~ "Complex Form Analogy",
    condition == "abpo" ~ "Absolute Position",
    condition == "repo" ~ "Relative Position",
    condition == "orob" ~ "Orientation of Object",
    condition == "orfe" ~ "Orientation of Feature",
    condition == "siob" ~ "Size of Object", 
    condition == "sife" ~ "Size of Feature", 
    condition == "nuob" ~ "Number of Object", 
    condition == "nufe" ~ "Number of Feature",
    TRUE ~ as.character(condition))) %>% 
  mutate(condition = factor(condition, levels = c(
    "Size of Object", # first level becomes reference
    "Size of Feature",
    "Number of Object",
    "Number of Feature"))) %>%
  mutate(item = factor(item, levels = c("4", "3", "2", "1")))

S3.item_intercepts <- add_colour(S3.item_intercepts)

S3.item.plot <- ggplot(S3.item_intercepts, aes(x = item, y = estimate)) +
  geom_point(aes(color = I(colour))) +
  geom_errorbar(aes(ymin = lower, ymax = upper, color = I(colour)), width = 0.6, size = .5) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "gray50") +
  coord_flip() +
  facet_wrap(~ condition, scales = "free_y", ncol = 1) +
  labs(
    x = "Item",
    y = "Estimated Deviation from Overall Intercept (log-odds)"
  ) +
  theme_minimal() +
  theme(
    legend.position = "none",  
    strip.text = element_text(size = 10, face = "bold"))

ggsave(
  filename = "../illustrations/plot_study3_item_intercepts.png",
  plot = S3.item.plot,
  device = "png",
  width = 6, height = 4,
  dpi = 300,
  units = "in",
  bg = "white"
)




```
